### ISSUE TITLE
Create Core Application Models

### ISSUE THREAD

**Issue by farzadasgari** [farzadasgari/CodeSkillz#1]
**Description:**

This issue outlines the creation of core application models to define essential details for the CodeSkillz project. These models will be responsible for storing and managing information like:

- Website Title
- Panel Title
- Logo Image
- Favicon
- Footer Text

**Additional Information:**

Feel free to include any specific requirements or design considerations for these models here.

**Comment by ZahraRezaei672** [comment]
Description : 

The typeface follows the rules of Pep 8 and is formatted accordingly.

From the __future__  class, imported unicode_literals to use different languages.

We defined verbose_name_plural in the meta class

 In models.py:

- The title of the website is defined for the site and the admin panel, and Cherfield is used for their model field.

- Browser is also defined for the site with Cherfield.

- Cherfield and text field are used for logo name and logo URL, respectively

- For the favicon name, a field is used, and for its URL, a text field is used

- For copyright, it is also defined with a text field


- and finally self.website_title return to the administrator

In admin.py:

  We displayed the relevant model in such a way that the items defined in models.py are supposed to remain constant.

**Comment by farzadasgari** [comment]
### Further Demands
This new comment outlines the addition of two logo models to support light and dark mode functionality within the CodeSkillz project.

**Light Mode Logo**: A logo specifically designed for use on light backgrounds within the user interface.
**Dark Mode Logo**: A logo designed for optimal visibility on dark backgrounds.

### Benefits

**Improved user experience**: Providing separate logos for light and dark mode ensures consistent visual appeal and readability across different user preferences.
**Enhanced accessibility**: Light and dark mode logos cater to users with visual impairments who may benefit from increased contrast.

**Comment by ZahraRezaei672** [comment]
In this new amendment :

 light_logo and light_logo_url defined for Light Mode Logo also dark_logo and dark_logo_url for Dark Mode Logo.
Cherfield and text field are used for logo name and logo URL, respectively.
