### ISSUE TITLE
Implement Core Application Models Form

### ISSUE THREAD

**Issue by farzadasgari** [farzadasgari/CodeSkillz#10]
### Description
This issue builds upon the previously discussed "Create Core Application Models" (#1) and outlines the development of a form using forms.py. This form will allow super admins to create and manage the core application models.

### Models
Main Model of the core app main.
The form should enable the super admin to enter data for each of the listed models.

Consider incorporating appropriate validation mechanisms to ensure data integrity (e.g., checking for valid image formats for logo and favicon uploads).

### Implementation
ConsiderationsUtilize Django Forms to streamline form creation and validation.
Determine the most appropriate approach for handling image uploads (`django.core.files.storage.FileSystemStorage` will be used for this project).

### Testing
Verify that the form successfully captures super admin input for all required fields.
Ensure proper validation functionality prevents the submission of invalid data. Test image upload functionality (if applicable) to confirm successful uploads and storage.

### Additional Information
If there are any specific design preferences or layout requirements for the form, please mention them here. Outline any error-handling logic or user feedback mechanisms planned for the form.

**Comment by ZahraRezaei672** [comment]
**Description** 
Forms.py was created for form development.
This form in the admin panel allows super admins to handle the models that were created in models.py.

**Steps** 

- First, _forms_ was imported from the _django_ class, and also from models.py , the Main class.

- The form class named MainForm was defined by inheriting from forms.ModelForm.

- By defining the Meta class and its attributes, model and fields, it was declared that the form should use what model and what fields.

**Note**

Fields are defined as --all-- to declare which fields of models are to be managed in the form.
