### ISSUE TITLE
Design Visual Assets

### ISSUE THREAD

**Issue by farzadasgari** [farzadasgari/CodeSkillz#2]
### Description
This issue outlines the creation of three key visual assets for the CodeSkillz project:

**Logo**: A logo that represents the identity and brand of CodeSkillz.
**Favicon**: A small icon that will be displayed in the browser tab and bookmark list for CodeSkillz.
**Readme Image**: An image to be included in the project's README file that effectively showcases CodeSkillz.

### Additional Considerations

**Consistency**: These visual assets should be designed with a consistent style and color scheme to create a cohesive brand identity for CodeSkillz.
**Quality**: The images should be high-resolution and visually appealing to create a professional impression.
**Specifications**: Please specify any particular size or format requirements for the logo and favicon.

**Comment by Amirdj3784** [comment]
I'm happy to announce that all design elements requested in this issue are now complete!
 • Branding Logo: A high-quality (2048x2048) and low-quality (512x512) version of the core branding logo have been designed.
 • Light & Dark Mode Logos: Corresponding high-quality and low-quality variations for both light and dark mode have also been created. These ensure consistent branding and optimal visibility across different user interface themes.
 • Favicon: A favicon sized appropriately for browser tabs and bookmark lists has been designed.
 • Readme Image: A high-resolution image specifically designed for the project's README file is also complete.
All assets are available for review in the following location: [https://github.com/farzadasgari/CodeSkillz/tree/main/media/CodeSkillz].
