### ISSUE TITLE
Design and Implement Custom Footer for User Template

### ISSUE THREAD

**Issue by farzadasgari** [farzadasgari/CodeSkillz#4]
### Description

This issue requests the design and implementation of a custom footer for the user template.  Currently, the user template lacks a footer, and this addition will enhance the overall user experience.

### Footer Design

**Responsibility**: Create a footer that visually complements the user template's design.
**Considerations**: The footer should be informative and visually appealing. It should also be responsive and optimized for various screen sizes.

### Implementation

After design approval, the footer will be integrated seamlessly into the user template.

**Technical Considerations**: Specify the development approach for integrating the footer (e.g., coding the footer directly into the template, using a separate component).

### Testing

Ensure the footer displays correctly across different browsers and devices.
Verify responsiveness and proper layout on various screen sizes.

### Additional Information

If there are any specific content requirements or branding guidelines for the footer, please mention them here.
Outline any desired functionalities for the footer beyond a static element (e.g., links, social media icons).

**Comment by mojikarimi** [comment]
The footer was added to the user template and the user interface was improved and all technical considerations were met. The footer has been tested in different sizes in different browsers
